/* ============================================================
   Golden State Travel Rx — destination library
   ------------------------------------------------------------
   DESIGN RULE (important, read before editing):
   This file contains NO specific vaccine or drug recommendations.
   Malaria/YF/food-water risk varies by REGION, SEASON and the
   traveler's own health — CDC says so explicitly. Country-level
   drug lists are misleading and go stale. So we publish:
     • a coarse, factual RISK PROFILE (sourced to CDC), and
     • a deep link to the official CDC destination page,
   and the specific plan is what the CONSULT produces.
   That is both the defensible position and the better funnel.

   mal:  0 = no current risk / malaria-free
         1 = risk in certain regions only (usually not main tourist areas)
         2 = risk in most areas
   food: 1 low · 2 moderate · 3 high (travelers' diarrhea risk)
   yf:   null, or a note (recommendation and/or entry-proof rule)
   alt:  null, or a note (altitude illness)
   Reviewed against CDC Yellow Book / Travelers' Health, July 2026.
   ============================================================ */

const DEST = {

/* ─────────── ASIA ─────────── */
japan:{name:"Japan",emoji:"🇯🇵",region:"Asia",aliases:["japan"],cdc:"japan",adv:"japan",flight:1100,day:180,peak:[3,4,10,11],low:[1,2,6],
  risk:{mal:0,malNote:"No malaria risk.",food:1,foodNote:"Low risk — food and water standards are excellent.",bug:false,
    yf:null,alt:null,other:"Typhoons (summer–autumn) and earthquakes are the main environmental hazards."},
  exp:[["Tokyo","Senso-ji Temple & Asakusa","spiritual","Tokyo's oldest temple at dawn"],
    ["Tokyo","Shibuya Crossing & Harajuku","culture","the world's busiest intersection"],
    ["Tokyo","teamLab digital art museum","culture","immersive light-and-water rooms"],
    ["Hakone","Hot springs & Mt Fuji views","nature","onsen under the mountain"],
    ["Kyoto","Fushimi Inari shrine","spiritual","thousands of vermilion gates"],
    ["Kyoto","Arashiyama bamboo grove","nature","towering green corridors"],
    ["Kyoto","Kinkaku-ji Golden Pavilion","history","gold temple on a mirror pond"],
    ["Osaka","Dotonbori street food","food","takoyaki, neon and canals"]]},

thailand:{name:"Thailand",emoji:"🇹🇭",region:"Asia",aliases:["thailand"],cdc:"thailand",adv:"thailand",flight:1000,day:75,peak:[12,1,2],low:[6,7,8,9],
  risk:{mal:1,malNote:"CDC reports NO malaria transmission in Bangkok, Chiang Mai, Chiang Rai, Pattaya, Ko Samui or the main Phuket resorts. Risk is confined to rural, forested areas along the Myanmar, Cambodia and Malaysia borders.",food:3,foodNote:"Moderate-to-high risk throughout, including in good hotels.",bug:true,bugNote:"Dengue year-round; Japanese encephalitis considered for longer or rural stays.",
    yf:"Proof of yellow fever vaccination may be required if you arrive from a country with YF risk.",alt:null,other:"Road and scooter crashes are the leading cause of injury to travelers."},
  exp:[["Bangkok","Grand Palace & Wat Pho","history","gilded halls & reclining Buddha"],
    ["Bangkok","Street food & tuk-tuks","food","the world's best night eats"],
    ["Chiang Mai","Old City temples","spiritual","hundreds of golden wats"],
    ["Chiang Mai","Ethical elephant sanctuary","nature","no riding, just rescue"],
    ["Phi Phi","Maya Bay island hopping","beach","turquoise limestone coves"],
    ["Phuket","Beaches & Big Buddha","beach","Andaman sunsets"],
    ["Ayutthaya","Ancient ruins day trip","history","temple ruins & stone Buddhas"],
    ["Bangkok","Floating & night markets","food","shop and eat from a boat"]]},

vietnam:{name:"Vietnam",emoji:"🇻🇳",region:"Asia",aliases:["vietnam"],cdc:"vietnam",adv:"vietnam",flight:1050,day:65,peak:[12,1,2,3],low:[6,7,8],
  risk:{mal:1,malNote:"Risk is limited to certain rural areas. CDC reports no transmission in the cities, the Red River and Mekong deltas, or the main coastal resort areas.",food:3,foodNote:"Moderate-to-high risk; food and water precautions matter.",bug:true,bugNote:"Dengue is widespread; Japanese encephalitis considered for rural or longer stays.",
    yf:"Proof of YF vaccination may be required if arriving from a country with YF risk.",alt:null,other:"Traffic is the single biggest day-to-day hazard."},
  exp:[["Hanoi","Old Quarter & street food","food","egg coffee & pho on plastic stools"],
    ["Ha Long Bay","Overnight cruise","nature","limestone karsts on emerald water"],
    ["Hoi An","Lantern-lit old town","culture","tailors, lanterns, riverside"],
    ["Hoi An","Cooking class & tailoring","food","learn the local kitchen"],
    ["Ho Chi Minh City","Cu Chi tunnels","history","the war underground"],
    ["Sapa","Rice-terrace trek","adventure","hill-tribe villages & green steps"],
    ["Hue","Imperial Citadel","history","Nguyen dynasty capital"],
    ["Mekong","Delta day trip","nature","floating markets & canals"]]},

indonesia:{name:"Indonesia (Bali)",emoji:"🇮🇩",region:"Asia",aliases:["indonesia","bali"],cdc:"indonesia",adv:"indonesia",flight:1150,day:80,peak:[7,8],low:[1,2],
  risk:{mal:1,malNote:"CDC reports NO malaria transmission in the Bali resort areas, Ubud, Jakarta or the Gili Islands. Risk is in eastern Indonesia (Papua, Maluku, East Nusa Tenggara) and rural Borneo, Sulawesi and Sumatra.",food:3,foodNote:"Moderate-to-high risk, including at good hotels.",bug:true,bugNote:"Dengue is common in Bali. Rabies is present — animal bites are a real concern.",
    yf:"Proof of YF vaccination may be required if arriving from a country with YF risk.",alt:null,other:"Scooter crashes and volcanic activity are the notable hazards."},
  exp:[["Ubud","Rice terraces & monkey forest","nature","emerald tiers & temples"],
    ["Ubud","Water temples & yoga","spiritual","Tirta Empul purification"],
    ["Canggu","Surf & beach clubs","beach","black-sand breaks"],
    ["Nusa Penida","Cliffs & snorkeling","adventure","Kelingking viewpoint"],
    ["Mt Batur","Sunrise volcano trek","adventure","above the clouds by dawn"],
    ["Uluwatu","Cliff temple & Kecak dance","spiritual","sunset fire ritual"],
    ["Seminyak","Spa & dining","food","warungs to fine dining"],
    ["Gili Islands","Island-hop day","beach","turtles & no traffic"]]},

india:{name:"India",emoji:"🇮🇳",region:"Asia",aliases:["india"],cdc:"india",adv:"india",flight:1050,day:60,peak:[11,12,1,2],low:[4,5,6],
  risk:{mal:2,malNote:"Malaria risk is present in most of the country below 2,000 m (6,500 ft) — including major cities. No transmission above 2,000 m (parts of Himachal, Sikkim, Ladakh, Uttarakhand).",food:3,foodNote:"High risk — food and water precautions are essential.",bug:true,bugNote:"Dengue and chikungunya are widespread; Japanese encephalitis considered for rural or longer stays; rabies is a real risk.",
    yf:"Proof of YF vaccination is required if arriving from a country with YF risk.",alt:"Himalayan itineraries (Leh, Ladakh) reach altitudes where acute mountain sickness is a genuine risk.",other:"One of the most consult-worthy destinations — especially for VFR travelers staying with family, who are at higher risk than resort tourists."},
  exp:[["Delhi","Red Fort & Old Delhi","history","Mughal grandeur & bazaars"],
    ["Agra","Taj Mahal at sunrise","history","the marble wonder"],
    ["Jaipur","Amber Fort & City Palace","history","the pink city's forts"],
    ["Jaipur","Bazaars & block-print shopping","culture","textiles and gems"],
    ["Varanasi","Ganges aarti ceremony","spiritual","fire ritual on the ghats"],
    ["Kerala","Backwater houseboat","nature","palm-lined canals"],
    ["Delhi","Street food & spice markets","food","chaat, kebabs, chai"],
    ["Udaipur","Lake Palace & City Palace","culture","romance on the water"]]},

pakistan:{name:"Pakistan",emoji:"🇵🇰",region:"Asia",aliases:["pakistan"],cdc:"pakistan",adv:"pakistan",flight:1300,day:55,peak:[4,5,9,10],low:[6,7],
  risk:{mal:2,malNote:"Malaria risk is present in most areas below 2,500 m, year-round.",food:3,foodNote:"High risk — food and water precautions are essential.",bug:true,bugNote:"Dengue outbreaks are frequent; rabies is present.",
    yf:"Proof of YF vaccination is required if arriving from a country with YF risk.",alt:"Northern areas (Hunza, Skardu, Karakoram) reach altitudes where altitude illness is a real risk.",other:"Advisory levels vary sharply by province — read the region-specific advisory carefully. A core VFR corridor."},
  exp:[["Lahore","Badshahi Mosque & Fort","history","Mughal capital splendor"],
    ["Lahore","Old City food street","food","the subcontinent's great kitchen"],
    ["Islamabad","Faisal Mosque & Margalla Hills","spiritual","modern capital under the hills"],
    ["Hunza","Karimabad & Baltit Fort","nature","the Karakoram valley"],
    ["Hunza","Attabad Lake & Passu Cones","nature","turquoise water, jagged peaks"],
    ["Skardu","Shangrila & Deosai plains","adventure","the roof of the world"],
    ["Taxila","Gandharan ruins","history","Buddhist archaeology"],
    ["Karachi","Coast & bazaars","culture","the port megacity"]]},

nepal:{name:"Nepal",emoji:"🇳🇵",region:"Asia",aliases:["nepal"],cdc:"nepal",adv:"nepal",flight:1250,day:55,peak:[10,11,3,4],low:[6,7,8],
  risk:{mal:1,malNote:"Risk is confined to the low-lying Terai districts. CDC reports no malaria transmission in Kathmandu or on typical high-altitude trekking routes.",food:3,foodNote:"High risk — food and water precautions are essential.",bug:true,bugNote:"Japanese encephalitis in the Terai; rabies is present.",
    yf:"Proof of YF vaccination required if arriving from a country with YF risk.",alt:"THE headline risk. Everest Base Camp, Annapurna and even Kathmandu-area treks reach altitudes where acute mountain sickness, HAPE and HACE are genuine dangers. Ascent profile and prophylaxis planning matter enormously.",other:"Altitude planning is the single most valuable part of a pre-travel consult here."},
  exp:[["Kathmandu","Durbar Square & Thamel","history","temple squares & alleys"],
    ["Kathmandu","Boudhanath & Pashupatinath","spiritual","the great stupa at dusk"],
    ["Pokhara","Phewa Lake & Annapurna views","nature","peaks over still water"],
    ["Everest region","Namche Bazaar trek","adventure","the gateway to Everest"],
    ["Annapurna","Poon Hill sunrise trek","adventure","sunrise over the Himalaya"],
    ["Chitwan","Jungle safari","nature","rhinos and tigers in the Terai"],
    ["Bhaktapur","Medieval city day trip","history","Newari architecture preserved"],
    ["Pokhara","Paragliding over the lake","adventure","fly with the Himalaya behind you"]]},

srilanka:{name:"Sri Lanka",emoji:"🇱🇰",region:"Asia",aliases:["sri lanka","srilanka"],cdc:"sri-lanka",adv:"sri-lanka",flight:1250,day:65,peak:[12,1,2,3],low:[5,6,10],
  risk:{mal:0,malNote:"WHO certified Sri Lanka malaria-free in 2016.",food:3,foodNote:"Moderate-to-high risk — food and water precautions still matter.",bug:true,bugNote:"Dengue is common and can be severe; Japanese encephalitis considered for rural or longer stays.",
    yf:"Proof of YF vaccination required if arriving from a country with YF risk.",alt:null,other:"A good example of why country-level assumptions fail: no malaria, but dengue is a genuine concern."},
  exp:[["Colombo","Galle Face & markets","culture","the coastal capital"],
    ["Sigiriya","Lion Rock fortress","history","a palace on a 600-ft monolith"],
    ["Kandy","Temple of the Tooth","spiritual","Buddhism's great relic"],
    ["Ella","Nine Arch Bridge & tea country","nature","emerald hills and trains"],
    ["Yala","Leopard safari","nature","the world's densest leopard population"],
    ["Galle","Dutch fort & ramparts","history","colonial walls over the sea"],
    ["Mirissa","Whale watching & beaches","beach","blue whales offshore"],
    ["Dambulla","Cave temple complex","spiritual","cave ceilings of golden Buddhas"]]},

philippines:{name:"Philippines",emoji:"🇵🇭",region:"Asia",aliases:["philippines"],cdc:"philippines",adv:"philippines",flight:1000,day:70,peak:[12,1,2,3],low:[7,8,9],
  risk:{mal:1,malNote:"Risk is limited to certain rural areas. CDC reports no transmission in Manila, other urban areas, or the main resort islands (including Boracay and Cebu city).",food:3,foodNote:"Moderate-to-high risk.",bug:true,bugNote:"Dengue is widespread; rabies is present.",
    yf:"Proof of YF vaccination required if arriving from a country with YF risk.",alt:null,other:"Typhoon season (roughly June–November) is a real planning factor. Some southern regions carry higher advisory levels."},
  exp:[["Manila","Intramuros walled city","history","Spanish colonial Manila"],
    ["Palawan","El Nido island hopping","beach","limestone lagoons"],
    ["Palawan","Underground river","nature","a UNESCO subterranean river"],
    ["Bohol","Chocolate Hills & tarsiers","nature","surreal hills, tiny primates"],
    ["Cebu","Kawasan Falls canyoneering","adventure","turquoise waterfall jumps"],
    ["Siargao","Cloud 9 surf break","beach","the surf capital"],
    ["Banaue","Rice terraces","culture","2,000-year-old engineering"],
    ["Boracay","White Beach sunset","beach","powder sand & sailboats"]]},

singapore:{name:"Singapore",emoji:"🇸🇬",region:"Asia",aliases:["singapore"],cdc:"singapore",adv:"singapore",flight:1100,day:170,peak:[6,7,12],low:[1,2],
  risk:{mal:0,malNote:"No malaria risk.",food:1,foodNote:"Low risk — food safety standards are world-class, including at hawker centers.",bug:true,bugNote:"Dengue is a genuine local risk despite the high standard of living.",
    yf:"Proof of YF vaccination required if arriving from a country with YF risk.",alt:null,other:"One of the safest destinations in the world. Note the strict drug laws — including for some prescription medications; verify before you fly."},
  exp:[["Singapore","Gardens by the Bay Supertrees","nature","a light show in a garden"],
    ["Singapore","Marina Bay Sands & skyline","culture","the infinity-pool icon"],
    ["Singapore","Hawker centre food crawl","food","Michelin-starred street food"],
    ["Singapore","Chinatown & Little India","culture","four cultures in one city"],
    ["Singapore","Sentosa Island","beach","beaches and theme parks"],
    ["Singapore","Botanic Gardens & orchids","nature","a UNESCO tropical garden"],
    ["Singapore","Night Safari","nature","a nocturnal zoo by tram"],
    ["Singapore","Kampong Glam & Arab St","culture","murals, mosque, boutiques"]]},

southkorea:{name:"South Korea",emoji:"🇰🇷",region:"Asia",aliases:["south korea","korea","republic of korea"],cdc:"south-korea",adv:"south-korea",flight:1000,day:140,peak:[4,5,10],low:[1,2,7],
  risk:{mal:1,malNote:"Very limited P. vivax risk in rural northern areas near the DMZ. CDC reports no risk in Seoul or typical tourist areas.",food:1,foodNote:"Low risk — excellent food and water standards.",bug:false,
    yf:null,alt:null,other:"Very safe. Air quality (spring dust) can matter for asthma and COPD travelers."},
  exp:[["Seoul","Gyeongbokgung Palace","history","changing of the royal guard"],
    ["Seoul","Bukchon Hanok Village","culture","tiled roofs & tea houses"],
    ["Seoul","Myeongdong & Gwangjang market","food","street food and skincare"],
    ["DMZ","Demilitarized Zone tour","history","the world's tensest border"],
    ["Busan","Gamcheon culture village","culture","the pastel hillside"],
    ["Busan","Haeundae Beach & seafood","beach","coastal city life"],
    ["Gyeongju","Ancient tombs & Bulguksa","history","Korea's museum without walls"],
    ["Jeju","Volcanic coast & Hallasan","nature","the island of stone and wind"]]},

cambodia:{name:"Cambodia",emoji:"🇰🇭",region:"Asia",aliases:["cambodia"],cdc:"cambodia",adv:"cambodia",flight:1150,day:60,peak:[11,12,1,2],low:[6,7,8,9],
  risk:{mal:1,malNote:"Risk is in rural forested areas. CDC reports no transmission in Phnom Penh or around Angkor Wat / Siem Reap city. Note: drug-resistant malaria is a known problem in western Cambodia.",food:3,foodNote:"High risk — food and water precautions are essential.",bug:true,bugNote:"Dengue is common; Japanese encephalitis considered for rural or longer stays; rabies is present.",
    yf:"Proof of YF vaccination required if arriving from a country with YF risk.",alt:null,other:"Landmines remain a hazard off marked paths in some rural provinces."},
  exp:[["Siem Reap","Angkor Wat at sunrise","history","the largest religious monument on earth"],
    ["Siem Reap","Ta Prohm & Bayon temples","history","tree roots and stone faces"],
    ["Siem Reap","Pub Street & night market","food","Khmer curry & river fish"],
    ["Phnom Penh","Royal Palace & Silver Pagoda","culture","the riverside capital"],
    ["Phnom Penh","Tuol Sleng & Killing Fields","history","a hard, necessary history"],
    ["Tonlé Sap","Floating villages","nature","life on a lake that breathes"],
    ["Battambang","Bamboo train & countryside","adventure","rural Cambodia by rail"],
    ["Koh Rong","Island beaches","beach","white sand & bioluminescence"]]},

maldives:{name:"Maldives",emoji:"🇲🇻",region:"Asia",aliases:["maldives"],cdc:"maldives",adv:"maldives",flight:1400,day:350,peak:[12,1,2,3],low:[6,7,8],
  risk:{mal:0,malNote:"WHO certified Maldives malaria-free in 2015.",food:1,foodNote:"Low risk at resorts; moderate on local islands.",bug:true,bugNote:"Dengue is present.",
    yf:"Proof of YF vaccination required if arriving from a country with YF risk.",alt:null,other:"Medical facilities on remote atolls are limited — evacuation insurance is worth real consideration. Diving raises decompression and flying-after-diving planning."},
  exp:[["Malé","Old Friday Mosque & fish market","culture","the compact capital"],
    ["North Atoll","Overwater villa & reef","beach","the classic Maldives"],
    ["Ari Atoll","Manta & whale shark snorkel","adventure","swim with giants"],
    ["Baa Atoll","Hanifaru Bay (seasonal)","nature","a UNESCO biosphere"],
    ["Maafushi","Local island & sandbank","beach","the non-resort Maldives"],
    ["Any atoll","Sunset dolphin cruise","nature","spinner dolphins at golden hour"],
    ["Any atoll","Night fishing & beach BBQ","food","reef fish grilled on the sand"],
    ["Any atoll","Bioluminescent beach walk","nature","the sea of stars"]]},

/* ─────────── EUROPE ─────────── */
italy:{name:"Italy",emoji:"🇮🇹",region:"Europe",aliases:["italy"],cdc:"italy",adv:"italy",flight:850,day:165,peak:[6,7,8],low:[11,12,1,2],
  risk:{mal:0,malNote:"No malaria risk.",food:1,foodNote:"Low risk.",bug:false,
    yf:null,alt:null,other:"Pickpocketing in tourist hubs; summer heat waves are increasingly a real health risk for older travelers."},
  exp:[["Rome","Colosseum & Roman Forum","history","2,000 years of empire"],
    ["Rome","Vatican & Sistine Chapel","culture","Michelangelo overhead"],
    ["Rome","Trastevere food walk","food","carbonara done right"],
    ["Florence","Uffizi Gallery & Duomo","culture","Renaissance, then climb the dome"],
    ["Venice","Grand Canal & St Mark's","history","the floating city"],
    ["Amalfi","Positano & the coast","beach","cliffside pastel villages"],
    ["Tuscany","Chianti wine country","food","vineyards and hill towns"],
    ["Rome","Trevi & Pantheon by night","culture","the city lit up"]]},

france:{name:"France",emoji:"🇫🇷",region:"Europe",aliases:["france"],cdc:"france",adv:"france",flight:800,day:175,peak:[6,7,8],low:[11,12,1,2],
  risk:{mal:0,malNote:"No malaria risk.",food:1,foodNote:"Low risk.",bug:false,
    yf:null,alt:"Chamonix and the Alps reach altitudes where mild altitude effects are possible.",other:"Pickpocketing around Paris landmarks; heat waves in summer."},
  exp:[["Paris","Eiffel Tower & Seine cruise","culture","the icon, then the river"],
    ["Paris","Louvre & Tuileries","culture","Mona Lisa and masterpieces"],
    ["Paris","Montmartre & Sacré-Cœur","culture","the artists' hill"],
    ["Versailles","Palace & gardens","history","Sun King opulence"],
    ["Loire","Château day trip","history","fairy-tale castles"],
    ["Nice","French Riviera","beach","azure coast & promenade"],
    ["Provence","Lavender & hill villages","nature","purple fields (summer)"],
    ["Paris","Le Marais food crawl","food","patisserie to wine bars"]]},

spain:{name:"Spain",emoji:"🇪🇸",region:"Europe",aliases:["spain"],cdc:"spain",adv:"spain",flight:750,day:150,peak:[6,7,8],low:[11,12,1],
  risk:{mal:0,malNote:"No malaria risk.",food:1,foodNote:"Low risk.",bug:false,
    yf:null,alt:null,other:"Pickpocketing in Barcelona and Madrid; extreme summer heat in the south."},
  exp:[["Barcelona","Sagrada Família","culture","Gaudí's unfinished masterpiece"],
    ["Barcelona","Park Güell & Gothic Quarter","culture","mosaic city above the sea"],
    ["Barcelona","Tapas & vermouth crawl","food","small plates, big nights"],
    ["Madrid","Prado & Retiro Park","culture","Velázquez and green lawns"],
    ["Seville","Real Alcázar & flamenco","history","Moorish palace, then the dance"],
    ["Granada","The Alhambra","history","the finest Moorish fortress"],
    ["San Sebastián","Pintxos in the old town","food","the Basque culinary capital"],
    ["Madrid","Mercado & late-night plazas","food","jamón, churros, midnight"]]},

greece:{name:"Greece",emoji:"🇬🇷",region:"Europe",aliases:["greece"],cdc:"greece",adv:"greece",flight:850,day:140,peak:[7,8],low:[11,12,1,2],
  risk:{mal:0,malNote:"No established malaria risk (rare isolated cases have been reported).",food:1,foodNote:"Low risk.",bug:false,
    yf:null,alt:null,other:"Summer heat and wildfires are genuine hazards; ferry motion sickness is the most common complaint."},
  exp:[["Athens","Acropolis & Parthenon","history","the birthplace of democracy"],
    ["Athens","Plaka old town","culture","neighborhoods under the rock"],
    ["Santorini","Oia sunset & caldera","beach","the famous blue domes"],
    ["Santorini","Wine & volcano boat","food","volcanic-soil vintages"],
    ["Mykonos","Beaches & windmills","beach","whitewashed island nights"],
    ["Delphi","The ancient oracle","history","ruins on Mt Parnassus"],
    ["Crete","Knossos & Minoan ruins","history","Europe's oldest palace"],
    ["Naxos","Village & beach day","beach","quieter Cycladic charm"]]},

portugal:{name:"Portugal",emoji:"🇵🇹",region:"Europe",aliases:["portugal"],cdc:"portugal",adv:"portugal",flight:750,day:130,peak:[6,7,8],low:[11,12,1],
  risk:{mal:0,malNote:"No malaria risk.",food:1,foodNote:"Low risk.",bug:false,
    yf:null,alt:null,other:"One of Europe's safest countries. Pickpocketing on Lisbon trams is the main note."},
  exp:[["Lisbon","Alfama & tram 28","culture","fado alleys and yellow trams"],
    ["Lisbon","Belém Tower & pastéis","food","the original custard tart"],
    ["Sintra","Pena Palace","history","a candy-colored hilltop palace"],
    ["Porto","Port wine cellars","food","tawny tastings on the Douro"],
    ["Douro","Valley wine cruise","nature","terraced vineyards"],
    ["Algarve","Benagil sea caves","nature","golden cliffs & grottoes"],
    ["Algarve","Beach day","beach","Atlantic coves"],
    ["Lisbon","LX Factory & miradouros","culture","viewpoints at golden hour"]]},

uk:{name:"United Kingdom",emoji:"🇬🇧",region:"Europe",aliases:["united kingdom","uk","britain","england","scotland"],cdc:"united-kingdom",adv:"united-kingdom",flight:750,day:190,peak:[6,7,8],low:[11,1,2],
  risk:{mal:0,malNote:"No malaria risk.",food:1,foodNote:"Low risk.",bug:false,
    yf:null,alt:null,other:"Very low health risk. Routine vaccines and travel-insurance planning are the main items."},
  exp:[["London","Tower of London & Bridge","history","the crown jewels"],
    ["London","Westminster & Buckingham Palace","culture","the changing of the guard"],
    ["London","British Museum","culture","the world under one roof"],
    ["London","Borough Market & pubs","food","the city's larder"],
    ["Bath","Roman Baths & Georgian city","history","the ancient thermal spring"],
    ["Edinburgh","Castle & Royal Mile","history","the volcanic-rock fortress"],
    ["Scotland","Highlands & Loch Ness","nature","glens, lochs and mist"],
    ["Oxford","Colleges day trip","culture","dreaming spires"]]},

germany:{name:"Germany",emoji:"🇩🇪",region:"Europe",aliases:["germany"],cdc:"germany",adv:"germany",flight:800,day:150,peak:[6,7,8,12],low:[1,2,11],
  risk:{mal:0,malNote:"No malaria risk.",food:1,foodNote:"Low risk.",bug:true,bugNote:"Tick-borne encephalitis in forested southern regions — relevant for hikers and campers.",
    yf:null,alt:null,other:"Very safe. TBE vaccination is worth discussing for outdoorsy itineraries in Bavaria."},
  exp:[["Berlin","Brandenburg Gate & Wall","history","the divided century"],
    ["Berlin","Museum Island","culture","five museums on one island"],
    ["Munich","Marienplatz & beer halls","food","pretzels and lager"],
    ["Bavaria","Neuschwanstein Castle","history","the fairy-tale castle"],
    ["Black Forest","Hiking & villages","nature","dark pines and cuckoo clocks"],
    ["Cologne","The cathedral & Rhine","history","Gothic on a grand scale"],
    ["Rhine Valley","Castle river cruise","nature","vineyards and fortresses"],
    ["Dresden","Baroque old town","culture","rebuilt from the ashes"]]},

switzerland:{name:"Switzerland",emoji:"🇨🇭",region:"Europe",aliases:["switzerland"],cdc:"switzerland",adv:"switzerland",flight:900,day:250,peak:[7,8,12,1],low:[4,5,11],
  risk:{mal:0,malNote:"No malaria risk.",food:1,foodNote:"Low risk.",bug:true,bugNote:"Tick-borne encephalitis in forested areas — relevant for hikers.",
    yf:null,alt:"Jungfraujoch (11,300 ft), Matterhorn viewpoints and high cable cars can trigger altitude symptoms, especially with rapid ascent.",other:"Extremely safe. Altitude and TBE are the two genuine clinical talking points."},
  exp:[["Zurich","Old Town & lake","culture","the elegant financial capital"],
    ["Lucerne","Chapel Bridge & Mt Pilatus","nature","the postcard lake town"],
    ["Interlaken","Jungfraujoch — Top of Europe","adventure","a railway to 11,300 ft"],
    ["Grindelwald","Alpine hiking & First Cliff","adventure","the Eiger over your shoulder"],
    ["Zermatt","The Matterhorn & Gornergrat","nature","the world's most famous peak"],
    ["Lauterbrunnen","Valley of 72 waterfalls","nature","cliffs and cascades"],
    ["Montreux","Lake Geneva & Chillon","history","a castle on the water"],
    ["Bern","Medieval capital","culture","UNESCO arcades and bears"]]},

iceland:{name:"Iceland",emoji:"🇮🇸",region:"Europe",aliases:["iceland"],cdc:"iceland",adv:"iceland",flight:750,day:230,peak:[6,7,8],low:[1,2,11],
  risk:{mal:0,malNote:"No malaria risk.",food:1,foodNote:"Low risk — some of the cleanest water on earth.",bug:false,
    yf:null,alt:null,other:"The real risks are environmental: weather exposure, hypothermia, river crossings, and driving on unfamiliar F-roads. Medical care is excellent but remote in the highlands."},
  exp:[["Reykjavík","Hallgrímskirkja & old harbor","culture","the northernmost capital"],
    ["Golden Circle","Geysir, Gullfoss & Þingvellir","nature","erupting geysers & continental rift"],
    ["Blue Lagoon","Geothermal spa","nature","milky-blue water in a lava field"],
    ["South Coast","Seljalandsfoss & black sand","nature","walk behind a waterfall"],
    ["Jökulsárlón","Glacier lagoon & Diamond Beach","nature","icebergs on black sand"],
    ["Vatnajökull","Ice cave & glacier hike","adventure","blue ice underfoot"],
    ["North","Whale watching (Húsavík)","nature","humpbacks in the Arctic"],
    ["Anywhere","Northern lights hunt (winter)","nature","aurora over the snow"]]},

croatia:{name:"Croatia",emoji:"🇭🇷",region:"Europe",aliases:["croatia"],cdc:"croatia",adv:"croatia",flight:900,day:120,peak:[7,8],low:[11,12,1,2],
  risk:{mal:0,malNote:"No malaria risk.",food:1,foodNote:"Low risk.",bug:true,bugNote:"Tick-borne encephalitis in some forested inland areas.",
    yf:null,alt:null,other:"Very safe. Sun and sea-related injuries (boat, cliff jumping) are the practical hazards."},
  exp:[["Dubrovnik","City walls & Old Town","history","the pearl of the Adriatic"],
    ["Dubrovnik","Cable car & island boat","nature","the coast from above"],
    ["Split","Diocletian's Palace","history","a Roman palace you live inside"],
    ["Plitvice","Lakes & waterfalls","nature","turquoise terraced lakes"],
    ["Hvar","Island beaches & lavender","beach","the sunniest island"],
    ["Krka","Waterfall national park","nature","swim below the falls"],
    ["Zagreb","Upper Town & markets","culture","the underrated capital"],
    ["Istria","Truffles & hill towns","food","Croatia's Tuscany"]]},

ireland:{name:"Ireland",emoji:"🇮🇪",region:"Europe",aliases:["ireland"],cdc:"ireland",adv:"ireland",flight:750,day:165,peak:[6,7,8],low:[11,1,2],
  risk:{mal:0,malNote:"No malaria risk.",food:1,foodNote:"Low risk.",bug:false,
    yf:null,alt:null,other:"Very low health risk. Coastal weather and driving on the left are the practical hazards."},
  exp:[["Dublin","Trinity College & Book of Kells","culture","the long room library"],
    ["Dublin","Temple Bar & pub session","food","live trad music and stout"],
    ["Cliffs of Moher","Atlantic cliffs","nature","700 ft straight down"],
    ["Galway","Latin Quarter & bay","culture","the west coast's heart"],
    ["Ring of Kerry","Coastal drive","nature","mountains meeting the sea"],
    ["Connemara","Wild landscapes","nature","bogs, lakes and stone walls"],
    ["Cork","Blarney Castle & English Market","history","kiss the stone"],
    ["Northern coast","Giant's Causeway","nature","40,000 basalt columns"]]},

/* ─────────── MIDDLE EAST & AFRICA ─────────── */
turkey:{name:"Türkiye (Turkey)",emoji:"🇹🇷",region:"Middle East",aliases:["turkey","turkiye","türkiye"],cdc:"turkey",adv:"turkey",flight:900,day:95,peak:[6,7,8,9],low:[12,1,2],
  risk:{mal:1,malNote:"CDC reports malaria risk in some parts of Türkiye. Risk has historically been confined to the southeastern provinces — the standard Istanbul–Cappadocia corridor is not a typical risk area. Confirm your specific route on the CDC page below.",food:2,foodNote:"Moderate risk — food and water precautions are worthwhile.",bug:false,
    yf:null,alt:"Cappadocia balloon flights are low-altitude; no significant altitude risk on standard itineraries.",other:"Advisory levels are much higher near the Syria/Iraq border — Istanbul and Cappadocia are the standard tourist corridor."},
  exp:[["Istanbul","Hagia Sophia","history","1,500 years of empire in one dome"],
    ["Istanbul","Blue Mosque & Hippodrome","spiritual","six minarets & Iznik tile"],
    ["Istanbul","Grand Bazaar","culture","4,000 shops of lanterns & rugs"],
    ["Istanbul","Bosphorus cruise","nature","sail between two continents"],
    ["Cappadocia","Hot-air balloon sunrise","adventure","hundreds of balloons over fairy chimneys"],
    ["Cappadocia","Cave hotels & valleys","nature","sleep in carved rock"],
    ["Ephesus","Ancient Roman city","history","the Library of Celsus"],
    ["Pamukkale","White travertine terraces","nature","thermal pools on a cliff"]]},

egypt:{name:"Egypt",emoji:"🇪🇬",region:"Middle East",aliases:["egypt"],cdc:"egypt",adv:"egypt",flight:950,day:90,peak:[10,11,12,1,2],low:[6,7,8],
  risk:{mal:0,malNote:"WHO certified Egypt malaria-free in October 2024.",food:3,foodNote:"High risk — food and water precautions are essential. This is the classic travelers'-diarrhea destination.",bug:true,bugNote:"Schistosomiasis in the Nile and canals — do not swim in fresh water.",
    yf:"Proof of YF vaccination required if arriving from a country with YF risk.",alt:null,other:"Extreme heat, and the advisory carries region-specific exceptions — read it carefully. Freshwater exposure (schistosomiasis) is an under-appreciated risk on Nile itineraries."},
  exp:[["Cairo","Pyramids of Giza & Sphinx","history","the last ancient wonder"],
    ["Cairo","Grand Egyptian Museum","culture","Tutankhamun's treasures"],
    ["Luxor","Valley of the Kings","history","the pharaohs' tombs"],
    ["Luxor","Karnak Temple","history","the great hypostyle hall"],
    ["Aswan","Nile felucca sail","nature","white sails at sunset"],
    ["Nile","Multi-day river cruise","nature","temples between Luxor & Aswan"],
    ["Abu Simbel","Ramses II temples","history","colossal rock-cut facades"],
    ["Red Sea","Hurghada diving","beach","coral reefs & clear water"]]},

morocco:{name:"Morocco",emoji:"🇲🇦",region:"Africa",aliases:["morocco"],cdc:"morocco",adv:"morocco",flight:800,day:90,peak:[3,4,5,10],low:[7,8],
  risk:{mal:0,malNote:"No current malaria risk.",food:3,foodNote:"Moderate-to-high risk — food and water precautions matter.",bug:false,
    yf:"Proof of YF vaccination may be required if arriving from a country with YF risk.",alt:"High Atlas treks (Toubkal, 13,600 ft) reach altitudes where altitude illness is a genuine risk.",other:"Desert heat, and rabies is present — animal bites need prompt attention."},
  exp:[["Marrakech","Jemaa el-Fnaa & souks","culture","snake charmers & lantern stalls"],
    ["Marrakech","Majorelle Garden & palaces","culture","a cobalt-blue oasis"],
    ["Fes","Medina & tanneries","history","the largest car-free old town on earth"],
    ["Sahara","Merzouga desert camp","adventure","camels & dunes under the stars"],
    ["Chefchaouen","The blue city","culture","indigo-washed mountain town"],
    ["Atlas Mts","Berber village trek","adventure","High Atlas trails"],
    ["Essaouira","Coastal ramparts","beach","a windswept Atlantic port"],
    ["Marrakech","Cooking class & hammam","food","tagine, then a steam"]]},

jordan:{name:"Jordan",emoji:"🇯🇴",region:"Middle East",aliases:["jordan"],cdc:"jordan",adv:"jordan",flight:1050,day:120,peak:[3,4,5,10,11],low:[7,8],
  risk:{mal:0,malNote:"No malaria risk.",food:2,foodNote:"Moderate risk — food and water precautions are worthwhile.",bug:false,
    yf:"Proof of YF vaccination required if arriving from a country with YF risk.",alt:null,other:"Extreme desert heat; Petra involves a lot of walking and sun. Regional advisory conditions can shift — check before booking."},
  exp:[["Petra","The Treasury through the Siq","history","a rose-red city half as old as time"],
    ["Petra","The Monastery climb","adventure","800 steps to the summit"],
    ["Wadi Rum","Desert jeep & Bedouin camp","adventure","Mars on earth"],
    ["Dead Sea","Float & mud spa","nature","the lowest point on earth"],
    ["Amman","Citadel & Roman theater","history","layers of empire"],
    ["Jerash","Roman ruins","history","the best-preserved Roman city outside Italy"],
    ["Aqaba","Red Sea diving","beach","coral on the Gulf"],
    ["Mount Nebo","Holy Land viewpoint","spiritual","where Moses saw the promised land"]]},

uae:{name:"United Arab Emirates",emoji:"🇦🇪",region:"Middle East",aliases:["united arab emirates","uae","dubai","abu dhabi"],cdc:"united-arab-emirates",adv:"united-arab-emirates",flight:1000,day:200,peak:[11,12,1,2,3],low:[6,7,8],
  risk:{mal:0,malNote:"No malaria risk.",food:1,foodNote:"Low risk — excellent food and water standards.",bug:false,
    yf:"Proof of YF vaccination may be required if arriving from a country with YF risk.",alt:null,other:"Extreme summer heat (120°F+). Very strict medication import laws — some common US prescriptions (and even codeine) are controlled here. Verify every medication before you fly; this is a genuine, under-appreciated trap."},
  exp:[["Dubai","Burj Khalifa observation deck","culture","the world's tallest building"],
    ["Dubai","Desert safari & dune bashing","adventure","4x4s and falcons at sunset"],
    ["Dubai","Old Dubai souks & abra","culture","gold, spice and a wooden boat"],
    ["Abu Dhabi","Sheikh Zayed Grand Mosque","spiritual","white marble and inlay"],
    ["Abu Dhabi","Louvre Abu Dhabi","culture","a dome that rains light"],
    ["Dubai","Palm Jumeirah & beach clubs","beach","the man-made island"],
    ["Dubai","Dubai Mall & fountains","culture","aquarium, ski slope, fountains"],
    ["Hatta","Mountain kayaking","nature","turquoise dam in the Hajar mountains"]]},

southafrica:{name:"South Africa",emoji:"🇿🇦",region:"Africa",aliases:["south africa"],cdc:"south-africa",adv:"south-africa",flight:1300,day:110,peak:[12,1,2],low:[6,7],
  risk:{mal:1,malNote:"Risk is confined to the low-lying northeast — Kruger National Park, northeastern Limpopo, Mpumalanga and far-northern KwaZulu-Natal — and is seasonal. CDC reports no risk in Cape Town, the Garden Route or Johannesburg.",food:2,foodNote:"Moderate risk.",bug:true,bugNote:"Tick-bite fever is common on safari and bush walks.",
    yf:"Proof of YF vaccination required if arriving from a country with YF risk (this catches many travelers routing through East Africa).",alt:null,other:"Kruger is the classic case where the malaria answer depends entirely on WHICH parts of the trip — and when. Crime and carjacking risk in urban areas."},
  exp:[["Cape Town","Table Mountain cable car","nature","the flat-topped icon"],
    ["Cape Town","Cape Point & Boulders penguins","nature","two oceans and a penguin colony"],
    ["Cape Winelands","Stellenbosch tasting","food","world-class wine an hour away"],
    ["Kruger","Big Five safari drives","nature","lion, leopard, rhino, elephant, buffalo"],
    ["Kruger","Sunrise game drive & bush walk","adventure","the bush on foot"],
    ["Garden Route","Coastal drive & Knysna","nature","forest meeting the sea"],
    ["Johannesburg","Apartheid Museum & Soweto","history","the hard, essential history"],
    ["Hermanus","Whale watching (seasonal)","nature","southern rights from the cliffs"]]},

kenya:{name:"Kenya",emoji:"🇰🇪",region:"Africa",aliases:["kenya"],cdc:"kenya",adv:"kenya",flight:1350,day:200,peak:[7,8,9,1,2],low:[4,5],
  risk:{mal:2,malNote:"Malaria risk is present in most areas, INCLUDING the game parks. Lower risk in Nairobi city and at altitudes above ~2,500 m.",food:3,foodNote:"High risk — food and water precautions are essential.",bug:true,bugNote:"Dengue, chikungunya; rabies is present; tick-bite fever on safari.",
    yf:"Yellow fever vaccination is generally RECOMMENDED for most of Kenya, and proof may be required for entry. This is a genuine required-planning destination.",alt:"Mt Kenya and some highland areas reach real altitude.",other:"This is the profile where a pre-travel consult is not optional — malaria prophylaxis and YF need planning weeks ahead."},
  exp:[["Nairobi","Elephant orphanage & giraffe centre","nature","conservation up close"],
    ["Maasai Mara","Great Migration game drives","nature","the greatest wildlife show on earth"],
    ["Maasai Mara","Hot-air balloon safari","adventure","dawn over the savanna"],
    ["Maasai Mara","Maasai village visit","culture","meet the community"],
    ["Amboseli","Elephants under Kilimanjaro","nature","the classic Africa photograph"],
    ["Lake Nakuru","Flamingos & rhino","nature","a pink lake"],
    ["Diani","Indian Ocean beach","beach","white sand after the bush"],
    ["Tsavo","Red elephants & Lugard Falls","nature","Kenya's vast wild heart"]]},

tanzania:{name:"Tanzania",emoji:"🇹🇿",region:"Africa",aliases:["tanzania","zanzibar"],cdc:"tanzania",adv:"tanzania",flight:1400,day:220,peak:[6,7,8,9,1,2],low:[4,5],
  risk:{mal:2,malNote:"Malaria risk is present throughout, including Serengeti, Ngorongoro and Zanzibar. Lower at high altitude on Kilimanjaro.",food:3,foodNote:"High risk — food and water precautions are essential.",bug:true,bugNote:"Dengue; rabies; tsetse flies in some parks.",
    yf:"Proof of YF vaccination is commonly required for entry, especially if arriving from or transiting a YF-risk country. Verify your exact routing.",alt:"Kilimanjaro (19,341 ft) is a serious altitude undertaking — ascent profile and prophylaxis planning are central, not optional.",other:"Kilimanjaro + safari + Zanzibar in one trip stacks altitude, malaria and food/water risk. The definition of a consult-worthy itinerary."},
  exp:[["Arusha","Gateway & coffee farms","culture","the safari launch point"],
    ["Serengeti","Migration & big-cat drives","nature","endless plains"],
    ["Serengeti","Balloon safari at dawn","adventure","float over the herds"],
    ["Ngorongoro","Crater floor game drive","nature","a caldera full of wildlife"],
    ["Kilimanjaro","Machame route trek","adventure","the roof of Africa, 19,341 ft"],
    ["Tarangire","Baobabs & elephant herds","nature","ancient trees, huge herds"],
    ["Zanzibar","Stone Town & spice tour","history","a Swahili trading city"],
    ["Zanzibar","Nungwi beach & dhow sunset","beach","turquoise Indian Ocean"]]},

/* ─────────── AMERICAS ─────────── */
mexico:{name:"Mexico",emoji:"🇲🇽",region:"Americas",aliases:["mexico"],cdc:"mexico",adv:"mexico",flight:450,day:110,peak:[12,1,2,3],low:[8,9],
  risk:{mal:1,malNote:"Risk is limited to certain rural states (e.g. parts of Chiapas, Chihuahua, Nayarit). CDC reports no risk in the major resort areas (Cancún, Riviera Maya, Los Cabos) or Mexico City.",food:3,foodNote:"Moderate-to-high risk — the classic travelers'-diarrhea destination.",bug:true,bugNote:"Dengue, Zika and chikungunya are present — Zika matters for pregnancy planning.",
    yf:"Proof of YF vaccination may be required if arriving from a country with YF risk.",alt:"Mexico City sits at 7,350 ft — mild altitude effects are common and often surprise travelers.",other:"The State Department advisory is STATE-BY-STATE — some states are Level 2, others Level 4. Your specific states are what matter, not the country."},
  exp:[["Mexico City","Zócalo & historic center","history","the Aztec-Spanish heart"],
    ["Mexico City","Teotihuacan pyramids","history","climb the Sun & Moon"],
    ["Mexico City","Roma-Condesa food tour","food","tacos al pastor & mezcal"],
    ["Oaxaca","Markets & mezcal","food","mole and craft spirits"],
    ["Riviera Maya","Cenote swimming","nature","crystal underground pools"],
    ["Tulum","Cliffside Maya ruins","history","temples over the Caribbean"],
    ["Chichén Itzá","El Castillo pyramid","history","a wonder of the world"],
    ["Cancún","Beach & reef day","beach","white sand & snorkeling"]]},

peru:{name:"Peru",emoji:"🇵🇪",region:"Americas",aliases:["peru"],cdc:"peru",adv:"peru",flight:700,day:95,peak:[6,7,8],low:[1,2,3],
  risk:{mal:1,malNote:"Risk is in the Amazon basin below ~2,000 m (Iquitos, Puerto Maldonado). CDC reports no malaria risk in Cusco, Machu Picchu or Lima.",food:3,foodNote:"High risk — food and water precautions are essential.",bug:true,bugNote:"Dengue in the lowlands and jungle.",
    yf:"Yellow fever vaccination is recommended for travel to jungle areas below ~2,300 m (Amazon, Puerto Maldonado, Iquitos). Not needed for Cusco/Machu Picchu/Lima alone.",alt:"THE headline risk. Cusco is 11,150 ft — higher than Machu Picchu itself. Rainbow Mountain tops 17,000 ft. Acute mountain sickness is extremely common here and is the #1 thing to plan for.",other:"The perfect illustration of itinerary-dependent risk: Cusco alone = altitude only. Add the Amazon = malaria + yellow fever too."},
  exp:[["Cusco","Acclimatize & San Blas","culture","cobblestones at 11,150 ft"],
    ["Sacred Valley","Pisac & Ollantaytambo","history","Inca terraces & ruins"],
    ["Machu Picchu","The lost citadel","history","the Andes' crown jewel"],
    ["Cusco","Rainbow Mountain trek","adventure","striped peaks above 17,000 ft"],
    ["Lima","Miraflores & the food scene","food","world-capital ceviche"],
    ["Lake Titicaca","Uros floating islands","culture","reed islands on the lake"],
    ["Cusco","Saqsaywamán ruins","history","megalithic Inca stonework"],
    ["Lima","Barranco art district","culture","murals & pisco bars"]]},

costarica:{name:"Costa Rica",emoji:"🇨🇷",region:"Americas",aliases:["costa rica"],cdc:"costa-rica",adv:"costa-rica",flight:550,day:130,peak:[12,1,2,3],low:[9,10],
  risk:{mal:1,malNote:"Very limited risk in a few rural areas (parts of Limón province). No risk in San José or the main tourist regions.",food:2,foodNote:"Moderate risk — generally good standards.",bug:true,bugNote:"Dengue and Zika are present — Zika matters for pregnancy planning.",
    yf:"Proof of YF vaccination is required if arriving from a country with YF risk (this catches travelers routing via Colombia, Brazil or Africa).",alt:null,other:"Adventure-injury risk (ziplining, rafting, surfing) is the practical hazard. Excellent medical care."},
  exp:[["San José","Central market & museums","culture","the compact capital"],
    ["Arenal","Volcano & hot springs","nature","lava-heated pools"],
    ["Arenal","Hanging bridges & zipline","adventure","the canopy from above"],
    ["Monteverde","Cloud forest reserve","nature","walk inside a cloud"],
    ["Manuel Antonio","Beach & sloth spotting","beach","rainforest meeting the Pacific"],
    ["Tortuguero","Turtle nesting & canals","nature","the Amazon of Costa Rica"],
    ["Osa","Corcovado wildlife","nature","the most biodiverse place on earth"],
    ["Tamarindo","Surf lesson & sunset","beach","Pacific breaks"]]},

brazil:{name:"Brazil",emoji:"🇧🇷",region:"Americas",aliases:["brazil"],cdc:"brazil",adv:"brazil",flight:900,day:110,peak:[12,1,2],low:[5,6,7],
  risk:{mal:1,malNote:"Risk is in the Amazon basin. CDC reports no malaria risk in Rio de Janeiro, São Paulo, or the Iguazu Falls area.",food:3,foodNote:"Moderate-to-high risk.",bug:true,bugNote:"Dengue is a major, recurring epidemic in Brazil; Zika and chikungunya too — Zika matters for pregnancy planning.",
    yf:"Yellow fever vaccination is RECOMMENDED for most of Brazil, including Iguazu Falls and areas near Rio and São Paulo. This is one of the most important YF destinations for US travelers.",alt:null,other:"YF vaccine needs ~10 days before travel to be effective — plan early. Urban crime is a real consideration in Rio and São Paulo."},
  exp:[["Rio de Janeiro","Christ the Redeemer & Corcovado","culture","the city from the statue's feet"],
    ["Rio de Janeiro","Sugarloaf cable car","nature","two peaks, one bay"],
    ["Rio de Janeiro","Copacabana & Ipanema","beach","the world's most famous sand"],
    ["Iguazu","The falls (Brazil side)","nature","275 waterfalls at once"],
    ["Amazon","Manaus jungle lodge","nature","the meeting of the waters"],
    ["Salvador","Pelourinho & capoeira","culture","Afro-Brazilian heart"],
    ["Paraty","Colonial town & islands","history","cobblestones and schooners"],
    ["São Paulo","Food scene & street art","food","South America's great kitchen"]]},

colombia:{name:"Colombia",emoji:"🇨🇴",region:"Americas",aliases:["colombia"],cdc:"colombia",adv:"colombia",flight:600,day:85,peak:[12,1,7,8],low:[4,5,10],
  risk:{mal:1,malNote:"Risk is in areas below ~1,700 m, particularly the Pacific and Amazon regions. CDC reports no malaria risk in Bogotá (8,600 ft) or Medellín city.",food:3,foodNote:"Moderate-to-high risk.",bug:true,bugNote:"Dengue, Zika and chikungunya — Zika matters for pregnancy planning.",
    yf:"Yellow fever vaccination is recommended for many areas, and some neighboring countries require proof of it if you're arriving FROM Colombia.",alt:"Bogotá is 8,600 ft — mild altitude effects are common.",other:"Advisory levels vary sharply by region; some departments are Level 4 while Medellín and Cartagena are standard tourist routes."},
  exp:[["Cartagena","Walled Old City","history","Caribbean colonial color"],
    ["Cartagena","Rosario Islands day trip","beach","turquoise Caribbean water"],
    ["Medellín","Comuna 13 & cable cars","culture","the transformation story"],
    ["Guatapé","El Peñol rock & lake","nature","740 steps, an unreal view"],
    ["Bogotá","La Candelaria & Gold Museum","culture","the high-altitude capital"],
    ["Coffee Region","Cocora Valley wax palms","nature","the world's tallest palms"],
    ["Coffee Region","Finca coffee tour","food","from cherry to cup"],
    ["Tayrona","Jungle-meets-Caribbean beaches","beach","hammocks under palms"]]},

argentina:{name:"Argentina",emoji:"🇦🇷",region:"Americas",aliases:["argentina"],cdc:"argentina",adv:"argentina",flight:950,day:100,peak:[12,1,2],low:[6,7],
  risk:{mal:0,malNote:"WHO certified Argentina malaria-free in 2019.",food:2,foodNote:"Moderate risk — generally good standards.",bug:true,bugNote:"Dengue outbreaks occur in the north.",
    yf:"Yellow fever vaccination is recommended for the northeast (Corrientes and Misiones — which includes IGUAZU FALLS). Not needed for Buenos Aires or Patagonia.",alt:"Andean crossings and Salta's high country reach real altitude.",other:"A textbook example: the same country needs YF vaccine for Iguazu and nothing for Buenos Aires."},
  exp:[["Buenos Aires","San Telmo & tango","culture","the milonga at midnight"],
    ["Buenos Aires","Recoleta & La Boca","history","Evita's tomb, painted streets"],
    ["Buenos Aires","Parrilla & Malbec night","food","the world's best steak"],
    ["Iguazu","The falls (Argentina side)","nature","the Devil's Throat up close"],
    ["Patagonia","Perito Moreno glacier","nature","a glacier that calves as you watch"],
    ["El Chaltén","Fitz Roy trek","adventure","Patagonia's granite spires"],
    ["Mendoza","Malbec wine country","food","vineyards under the Andes"],
    ["Salta","Northwest canyons & Cafayate","nature","red rock and high-altitude wine"]]},

dominicanrepublic:{name:"Dominican Republic",emoji:"🇩🇴",region:"Americas",aliases:["dominican republic"],cdc:"dominican-republic",adv:"dominican-republic",flight:550,day:120,peak:[12,1,2,3],low:[8,9,10],
  risk:{mal:1,malNote:"Low risk in some areas; higher in provinces bordering Haiti. Risk in the main resort areas (Punta Cana) is low but not zero — CDC guidance is worth checking for your exact route.",food:3,foodNote:"Moderate-to-high risk outside resorts.",bug:true,bugNote:"Dengue, Zika and chikungunya — Zika matters for pregnancy planning.",
    yf:"Proof of YF vaccination may be required if arriving from a country with YF risk.",alt:null,other:"Resort-only trips and independent travel carry very different risk profiles here."},
  exp:[["Punta Cana","Bávaro Beach & reef","beach","the classic Caribbean strip"],
    ["Santo Domingo","Zona Colonial","history","the oldest European city in the Americas"],
    ["Samaná","Whale watching (seasonal)","nature","humpbacks in the bay"],
    ["Samaná","El Limón waterfall ride","adventure","horseback to a jungle cascade"],
    ["Puerto Plata","Cable car & Fort","culture","the amber coast"],
    ["Bahía de las Águilas","Remote beach","beach","five miles of empty sand"],
    ["Jarabacoa","River rafting & mountains","adventure","the Dominican Alps"],
    ["Santo Domingo","Merengue & mercado","food","the island's rhythm"]]},

chile:{name:"Chile",emoji:"🇨🇱",region:"Americas",aliases:["chile"],cdc:"chile",adv:"chile",flight:900,day:120,peak:[12,1,2],low:[6,7],
  risk:{mal:0,malNote:"No malaria risk.",food:2,foodNote:"Low-to-moderate risk — good standards.",bug:false,
    yf:null,alt:"THE key risk. San Pedro de Atacama sits at 7,900 ft, with day trips to geysers above 14,000 ft. Altitude illness is common and often underestimated here.",other:"Easter Island and Patagonia are extremely remote — medical evacuation planning is worth real thought."},
  exp:[["Santiago","Bellavista & Cerro San Cristóbal","culture","the Andes over the city"],
    ["Valparaíso","Hillside murals & funiculars","culture","the painted port"],
    ["Atacama","Moon Valley & salt flats","nature","the driest desert on earth"],
    ["Atacama","El Tatio geysers at dawn","adventure","steam at 14,000 ft"],
    ["Atacama","Stargazing in the desert","nature","the clearest sky on the planet"],
    ["Patagonia","Torres del Paine W trek","adventure","granite towers and glaciers"],
    ["Casablanca","Wine valley tasting","food","cool-climate Chilean whites"],
    ["Chiloé","Stilt houses & churches","culture","wooden UNESCO churches"]]},

/* ─────────── OCEANIA ─────────── */
australia:{name:"Australia",emoji:"🇦🇺",region:"Oceania",aliases:["australia"],cdc:"australia",adv:"australia",flight:1300,day:170,peak:[12,1,2],low:[6,7],
  risk:{mal:0,malNote:"No malaria risk.",food:1,foodNote:"Low risk — excellent standards.",bug:true,bugNote:"Ross River virus and (rarely) Japanese encephalitis in the tropical north.",
    yf:"Proof of YF vaccination is required if arriving from a country with YF risk.",alt:null,other:"The real risks are environmental: extreme sun/UV (the world's highest skin-cancer rates), marine stingers in the tropical north, and heat. Reef diving raises flying-after-diving planning."},
  exp:[["Sydney","Opera House & Harbour Bridge","culture","the world's great harbor"],
    ["Sydney","Bondi to Coogee coastal walk","beach","clifftop path and ocean pools"],
    ["Great Barrier Reef","Snorkel or dive the reef","adventure","the largest living structure on earth"],
    ["Cairns","Daintree rainforest","nature","the oldest rainforest in the world"],
    ["Uluru","Sunrise at the rock","spiritual","the red heart of the country"],
    ["Melbourne","Laneways & coffee culture","food","street art and flat whites"],
    ["Great Ocean Rd","Twelve Apostles","nature","limestone stacks in the Southern Ocean"],
    ["Tasmania","Cradle Mountain hike","adventure","wild alpine wilderness"]]},

newzealand:{name:"New Zealand",emoji:"🇳🇿",region:"Oceania",aliases:["new zealand"],cdc:"new-zealand",adv:"new-zealand",flight:1350,day:160,peak:[12,1,2],low:[6,7],
  risk:{mal:0,malNote:"No malaria risk.",food:1,foodNote:"Low risk — excellent standards.",bug:false,
    yf:null,alt:"Southern Alps hiking reaches moderate altitude; generally not a major concern.",other:"Extremely safe. Adventure-sport injury (bungee, skydiving, canyoning, hiking) is the genuine hazard — and intense UV."},
  exp:[["Auckland","Sky Tower & harbor","culture","the city of sails"],
    ["Rotorua","Geothermal parks & Māori culture","spiritual","geysers and a hāngī feast"],
    ["Waitomo","Glowworm caves","nature","a galaxy underground"],
    ["Queenstown","Bungee & jet boat","adventure","the adventure capital of the world"],
    ["Milford Sound","Fiord cruise","nature","sheer walls and waterfalls"],
    ["Wanaka","Roys Peak hike","adventure","the most photographed view in NZ"],
    ["Franz Josef","Glacier heli-hike","adventure","ice in a rainforest"],
    ["Hobbiton","Movie set tour","culture","the Shire, preserved"]]},

fiji:{name:"Fiji",emoji:"🇫🇯",region:"Oceania",aliases:["fiji"],cdc:"fiji",adv:"fiji",flight:1100,day:190,peak:[6,7,8,12],low:[1,2,3],
  risk:{mal:0,malNote:"No malaria risk.",food:2,foodNote:"Moderate risk outside resorts.",bug:true,bugNote:"Dengue, Zika and chikungunya are present — Zika matters for pregnancy planning.",
    yf:"Proof of YF vaccination may be required if arriving from a country with YF risk.",alt:null,other:"Remote islands have very limited medical care — evacuation insurance deserves serious thought. Cyclone season runs roughly November–April."},
  exp:[["Nadi","Garden of the Sleeping Giant","nature","orchids under the hills"],
    ["Mamanuca","Island hopping & snorkel","beach","the postcard islands"],
    ["Yasawa","Blue Lagoon & village visit","culture","a kava ceremony with the village"],
    ["Taveuni","Rainbow Reef diving","adventure","soft-coral capital of the world"],
    ["Beqa","Shark dive (advanced)","adventure","bull sharks, no cage"],
    ["Coral Coast","Sigatoka dunes & beaches","nature","surf and archaeology"],
    ["Suva","Markets & museum","culture","the Pacific's biggest city"],
    ["Anywhere","Sunset sail & lovo feast","food","earth-oven cooking on the sand"]]}

};
